config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :members
  resources :cassettes
  resources :casts
  resources :movies
  resources :actors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cast.rb
class Cast < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :set_cast, only: [:show, :edit, :update, :destroy]

  # GET /casts
  # GET /casts.json
  def index
    @casts = Cast.all
  end

  # GET /casts/1
  # GET /casts/1.json
  def show
  end

  # GET /casts/new
  def new
    @cast = Cast.new
  end

  # GET /casts/1/edit
  def edit
  end

  # POST /casts
  # POST /casts.json
  def create
    @cast = Cast.new(cast_params)

    respond_to do |format|
      if @cast.save
        format.html { redirect_to @cast, notice: 'Cast was successfully created.' }
        format.json { render :show, status: :created, location: @cast }
      else
        format.html { render :new }
        format.json { render json: @cast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casts/1
  # PATCH/PUT /casts/1.json
  def update
    respond_to do |format|
      if @cast.update(cast_params)
        format.html { redirect_to @cast, notice: 'Cast was successfully updated.' }
        format.json { render :show, status: :ok, location: @cast }
      else
        format.html { render :edit }
        format.json { render json: @cast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casts/1
  # DELETE /casts/1.json
  def destroy
    @cast.destroy
    respond_to do |format|
      format.html { redirect_to casts_url, notice: 'Cast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cast
      @cast = Cast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cast_params
      params.require(:cast).permit(:movie_id, :actor_id)
    end
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/views/casts/_form.html.erb
<%= form_with(model: cast, local: true) do |form| %>
  <% if cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
      <% cast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id %>
  </div>

  <div class="field">
    <%= form.label :actor_id %>
    <%= form.text_field :actor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casts/edit.html.erb
<h1>Editing Cast</h1>

<%= render 'form', cast: @cast %>

<%= link_to 'Show', @cast %> |
<%= link_to 'Back', casts_path %>

app/views/casts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Casts</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Actor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casts.each do |cast| %>
      <tr>
        <td><%= link_to cast.movie.title, cast.movie %></td>
        <td><%= link_to cast.actor.name, cast.actor %></td>
        <td><%= link_to 'Show', cast %></td>
        <td><%= link_to 'Edit', edit_cast_path(cast) %></td>
        <td><%= link_to 'Destroy', cast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cast', new_cast_path %>

app/views/casts/new.html.erb
<h1>New Cast</h1>

<%= render 'form', cast: @cast %>

<%= link_to 'Back', casts_path %>

app/views/casts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= link_to @cast.movie.title, @cast.movie %>
</p>

<p>
  <strong>Actor:</strong>
  <%= link_to @cast.actor.name, @cast.actor %>
</p>

<%= link_to 'Edit', edit_cast_path(@cast) %> |
<%= link_to 'Back', casts_path %>